version: "3"

services: # Services to run in Docker Container
  app: # Application to run in Docker
    build:
      context: . # Context of the Application '.' means current directory
    ports:
      - "8000:8000" # Mapping 8000 port of local to the 8000 port of Docker
    volumes:
      - ./app:/app # Watching changes in ./app of local to reflect in Docker 
    command: 
      # Running shell command in Docker to start server
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=iamawesome
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamawesome